package com.free.moreletter.dao.mapper;

import com.free.moreletter.dao.model.CategoryDo;
import com.free.moreletter.dao.model.CategoryDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_category
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    long countByExample(CategoryDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_category
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int deleteByExample(CategoryDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_category
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int insert(CategoryDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_category
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int insertSelective(CategoryDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_category
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    List<CategoryDo> selectByExample(CategoryDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_category
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") CategoryDo record, @Param("example") CategoryDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_category
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int updateByExample(@Param("record") CategoryDo record, @Param("example") CategoryDoExample example);
}