package com.free.moreletter.dao.mapper;

import java.util.List;

import com.free.moreletter.dao.model.ImgDo;
import com.free.moreletter.dao.model.ImgDoExample;
import org.apache.ibatis.annotations.Param;

public interface ImgDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbg.generated Sun Feb 24 16:42:17 CST 2019
     */
    long countByExample(ImgDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbg.generated Sun Feb 24 16:42:17 CST 2019
     */
    int deleteByExample(ImgDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbg.generated Sun Feb 24 16:42:17 CST 2019
     */
    int insert(ImgDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbg.generated Sun Feb 24 16:42:17 CST 2019
     */
    int insertSelective(ImgDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbg.generated Sun Feb 24 16:42:17 CST 2019
     */
    List<ImgDo> selectByExample(ImgDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbg.generated Sun Feb 24 16:42:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") ImgDo record, @Param("example") ImgDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbg.generated Sun Feb 24 16:42:17 CST 2019
     */
    int updateByExample(@Param("record") ImgDo record, @Param("example") ImgDoExample example);
}