package com.free.moreletter.dao.mapper;

import com.free.moreletter.dao.model.ShareHistDo;
import com.free.moreletter.dao.model.ShareHistDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ShareHistDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_share_hist
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    long countByExample(ShareHistDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_share_hist
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int deleteByExample(ShareHistDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_share_hist
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int insert(ShareHistDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_share_hist
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int insertSelective(ShareHistDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_share_hist
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    List<ShareHistDo> selectByExample(ShareHistDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_share_hist
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShareHistDo record, @Param("example") ShareHistDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_share_hist
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int updateByExample(@Param("record") ShareHistDo record, @Param("example") ShareHistDoExample example);
}