package com.free.moreletter.dao.mapper;

import com.free.moreletter.dao.model.TagDo;
import com.free.moreletter.dao.model.TagDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    long countByExample(TagDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int deleteByExample(TagDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int insert(TagDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int insertSelective(TagDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    List<TagDo> selectByExample(TagDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") TagDo record, @Param("example") TagDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int updateByExample(@Param("record") TagDo record, @Param("example") TagDoExample example);
}