package com.free.moreletter.dao.mapper;

import com.free.moreletter.dao.model.ThirdPlatformInfoDo;
import com.free.moreletter.dao.model.ThirdPlatformInfoDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ThirdPlatformInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    long countByExample(ThirdPlatformInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int deleteByExample(ThirdPlatformInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int insert(ThirdPlatformInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int insertSelective(ThirdPlatformInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    List<ThirdPlatformInfoDo> selectByExample(ThirdPlatformInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") ThirdPlatformInfoDo record, @Param("example") ThirdPlatformInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int updateByExample(@Param("record") ThirdPlatformInfoDo record, @Param("example") ThirdPlatformInfoDoExample example);
}