package com.free.moreletter.dao.mapper;

import com.free.moreletter.dao.model.UserDo;
import com.free.moreletter.dao.model.UserDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_user
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    long countByExample(UserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_user
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int deleteByExample(UserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_user
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int insert(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_user
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int insertSelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_user
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    List<UserDo> selectByExample(UserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_user
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserDo record, @Param("example") UserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_user
     *
     * @mbg.generated Sun Feb 24 17:27:33 CST 2019
     */
    int updateByExample(@Param("record") UserDo record, @Param("example") UserDoExample example);
}